### ISSUE TITLE
The factor enum of Generator is inconsistent between swift-2.3 and swift-3

### ISSUE THREAD

**Issue by mxie1563** [mattrubin/OneTimePassword#121]
In Swift-2.3 branch, the enum is {.Counter, .Timer}
In Swift-3 branch, the enum is {.counter, .timer}

**Comment by mattrubin** [comment]
As per the [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/#follow-case-conventions), only type and protocol names should begin with an uppercase letter. Enums and static members in the Swift standard library were converted to lower camel case [in Swift 3](https://github.com/apple/swift-evolution/blob/master/proposals/0006-apply-api-guidelines-to-the-standard-library.md) and OneTimePassword enums will follow the same guidelines from 3.0 onwards.
