### ISSUE TITLE
Use of unresolved identifier 'HMAC'

### ISSUE THREAD

**Issue by chrisiona** [mattrubin/OneTimePassword#136]
Hi there,

I installed your lib using CocoaPods;  It's reporting an issue with resolving the HMAC function.

```pod 'OneTimePassword', '~> 3.0'```

![image](https://cloud.githubusercontent.com/assets/1732182/22879484/551a02fe-f232-11e6-97cf-a9b758c7e686.png)

Is this a known issue?

Thanks.

**Comment by chrisiona** [comment]
I should note that I'm using Swift 3 with Xcode 8.2.1, and that I'm not calling the library yet — this error occurs after installation with CocoaPods.  Thanks again.

**Comment by mattrubin** [comment]
I haven't been able to reproduce this issue with Swift 3, Xcode 8.2.1, and CocoaPods 1.1.1.

That missing function is defined in the OneTimePassword file `Crypto.swift`. Can you check to see that file is included in the target CocoaPods created?

Are you installing the library in a new project, or updating from a 2.x version of the library? That `Crypto.swift` file was added to the project in version 2.0.1, so unless you're updating directly from OneTimePassword 2.0 to 3.0 and skipping the intermediate versions, I'm not sure why that file wouldn't already be included.

**Comment by chrisiona** [comment]
Thanks @mattrubin, it was strange.

I deleted the pods directory and ran ```pod install``` and it works now.  I'm guessing it was a bad install.
