### ISSUE TITLE
Redefinition of module 'CommonCrypto'

### ISSUE THREAD

**Issue by onunix** [mattrubin/OneTimePassword#140]
I make a framework named my_framework.framework  ,my_framework.framework  called the onetimepassword, all seems  is ok,  but  when a app  call my_framework.framework ,it hint: missing CommonCrypto, then i add CommonCrypto to my app ,and go to Build Settings, Swift Compiler – Search Paths and set Import Paths to point to the directory that contains the CommonCrypto directory. then i get the error:  

..../Pods/OneTimePassword/CommonCrypto/iphonesimulator/module.modulemap:1:8: Redefinition of module 'CommonCrypto'

**Comment by mattrubin** [comment]
I don't think you need to add the CommonCrypto module map directory to your import paths – linking the OneTimePassword framework which imports the module map should be enough. Can you try removing the extra import path setting you added to your application?
