### ISSUE TITLE
Generating wrong code

### ISSUE THREAD

**Issue by WillBishop** [mattrubin/OneTimePassword#143]
Hi very new to this library but I have an issue.

I take an otpauth:// url, and generate a token from it, except it is generating the wrong password.

I am getting it from this website:
https://daplie.github.io/browser-authenticator/

```
let url = URL(string: metadataObj.stringValue)
				
if let token = Token(url: url!) {
	print("Password: \(token.currentPassword!)") //This prints the wrong code
	print("Name: \(token.issuer)")					
}
```

Any ideas?

**Comment by mattrubin** [comment]
At a glance, I don't see anything wrong with your code. Is it possible the password had expired by the time you read it from your logs and tried to verify it?

I tried creating and validating a token from that website using [Authenticator](https://github.com/mattrubin/Authenticator) (an open source app which uses this library), and it worked fine. You can check out the source to see see an example of how that app [scans the QR code](https://github.com/mattrubin/Authenticator/blob/2.0.0/Authenticator/Source/QRScanner.swift#L108-L123) and [builds a `Token`](https://github.com/mattrubin/Authenticator/blob/2.0.0/Authenticator/Source/TokenScanner.swift#L79-L83), and hopefully that will help.

**Comment by WillBishop** [comment]
Hmm.

Looking at that code, I'm not sure what's wrong. 

I updated the code a bit:

```
func handleOTP(_ otpurl: String){
	let url = URL(string: otpurl)
			
	if let token = Token(url: url!){
		print("Password: ", token.currentPassword)
	}
}
```

func captureOutput(_ captureOutput: AVCaptureOutput!, didOutputMetadataObjects metadataObjects: [Any]!, from connection: AVCaptureConnection!) {
		
	if metadataObjects == nil || metadataObjects.count == 0 {
		qrCodeFrameView?.frame = CGRect.zero
		return
	}
		
	let metadataObj = metadataObjects[0] as! AVMetadataMachineReadableCodeObject
		
		
	if metadataObj.type == AVMetadataObjectTypeQRCode {
		let barCodeObject = videoPreviewLayer?.transformedMetadataObject(for: metadataObj)
		qrCodeFrameView?.frame = barCodeObject!.bounds
			
		if metadataObj.stringValue != nil {
				
			DispatchQueue.main.async {
				self.handleOTP(metadataObj.stringValue)
			}
				
				
			AudioServicesPlayAlertSound(SystemSoundID(kSystemSoundID_Vibrate))
			self.captureSession?.stopRunning()
			videoPreviewLayer?.removeFromSuperlayer()
			qrCodeFrameView?.removeFromSuperview()
		}
	}
}
```

The codes don't work, and I'm quick enough for them not to expire

**Comment by WillBishop** [comment]
Ok little update,

it seems the website I linked is the only one it doesn't work on
