### ISSUE TITLE
How to generate a 5 digit TOTP ?

### ISSUE THREAD

**Issue by AmberKCopper** [mattrubin/OneTimePassword#145]
I've tried the following logic, but it fails when I try to create 5 digit OTP.

`let secret = "fvfsdvfsvdfbedfgvdfbgvdbvgfbdvbgvtgnbvcxbgIvnlsn"
        // base 32
        guard let secretData = MF_Base32Codec.data(fromBase32String: secret),
            !secretData.isEmpty else {
                print("Invalid secret")
                return
        }
        
        if let totp = Generator(factor: .timer(period: 30), secret: secretData, algorithm: .sha1, digits: 5)
             {
            
                let pasword = try! totp.password(at: Date())
                print(pasword)
                
        } else {
            print("Failed to Generate.")
        }`

**Comment by mattrubin** [comment]
The Generator type validates the digit count to ensure it is at least 6: https://github.com/mattrubin/OneTimePassword/blob/develop/Sources/Generator.swift#L218-L223

Is there a specific website or service you've discovered that uses 5-digit one-time passwords?
