### ISSUE TITLE
Could not build Objective-C module 'CommonCrypto.h' 

### ISSUE THREAD

**Issue by twjazzhuang** [mattrubin/OneTimePassword#165]
I usd Xcode 9.2 & cocoapods OneTimePassword 3.1
In module.map need change Path
 "iPhoneOS.sdk" to "iPhoneSimulator11.2.sdk", 
then It will work fine.

**Comment by mattrubin** [comment]
Interesting... is this a fresh install of Xcode? Are you building for device or simulator? Can you please share the full build log with the error when you try to build with the original module map?

**Comment by twjazzhuang** [comment]
I'm building for device iPhone7 11.2.6.
there is bulid log.
[Build testlog_2018-03-29T15-30-28.rtf.zip](https://github.com/mattrubin/OneTimePassword/files/1859007/Build.testlog_2018-03-29T15-30-28.rtf.zip)

**Comment by mattrubin** [comment]
This seems to be an issue with the way we attempt to inject the path to the header if Xcode is installed in a non-standard location. By default, the module map references the headers inside `/Applications/Xcode.app/Contents/Developer`, but the [`injectXcodePath.sh`](https://github.com/mattrubin/OneTimePassword/blob/develop/CommonCrypto/injectXcodePath.sh) script uses `xcode-select -p` to detect if the user is using an Xcode that is not at `/Applications/Xcode.app`.

Based on your error logs, it seems that on your machine the result of `xcode-select -p` is `/Library/Developer/CommandLineTools`, which is unexpected. (On my machine, `xcode-select` refuses to let me use that path, printing "error: invalid developer directory".) Can you please run `xcode-select -p` and confirm the output?

It would also be helpful if you could:
 - List the contents of `/Applications/Xcode.app/Contents/Developer/Platforms/`
 - List the contents of `/Library/Developer/CommandLineTools/Platforms/`
 - If you don't have `xcode-select` set to the non-standard directory intentionally, try running `sudo xcode-select -s /Applications/Xcode.app` to reset the default developer directory path.

**Comment by twjazzhuang** [comment]
sudo xcode-select -s /Applications/Xcode.app 
it's work.
many thanks!!!
