### ISSUE TITLE
I a getting this error on adding the pod

### ISSUE THREAD

**Issue by mthooyavan** [mattrubin/OneTimePassword#171]
module CommonCrypto [system] {
    header "/Library/Developer/CommandLineTools/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonCrypto.h"
    export *
}

**Comment by mattrubin** [comment]
This looks like it might be the same issue as #165. Try running the following command in the terminal to reset the default developer directory path:
```
sudo xcode-select -s /Applications/Xcode.app
```

**Comment by mthooyavan** [comment]
Thank you for the help.

Thank you,
—————————————————————————————————
Thooyavan Manivaasakar,
Bangalore.

[redacted]


CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use , disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message(S).
