### ISSUE TITLE
pod 3.1.2 version is not working in xcode 9.3

### ISSUE THREAD

**Issue by RaviMalviya** [mattrubin/OneTimePassword#178]
Inside Crypto.swift file having import CommonCrypto.
The error is like Could not build Objective-C module 'CommonCrypto'

please help me out

**Comment by mattrubin** [comment]
What about it isn't working? What error messages are you seeing? Can you include any logs?

**Comment by RaviMalviya** [comment]
pod showing such error inside the library, I had just upgraded from OneTimePassword pod 3.1.1 to 3.1.2.

**Comment by mattrubin** [comment]
This looks like it might be the same issue as #165. Try running the following command in the terminal to reset the default developer directory path:
```
sudo xcode-select -s /Applications/Xcode.app
```
