### ISSUE TITLE
How to refresh the counter?

### ISSUE THREAD

**Issue by moQingTing** [mattrubin/OneTimePassword#183]
Hello, I have a problem, just don't know how to refresh the one-time password based on counter

**Comment by mattrubin** [comment]
If you're looking to update a counter-based token, it's as simple as calling the `Token`'s `updatedToken()` method. Don't forget to save the updated token back to the keychain using the same persistent identifier!

Some example code for how [Authenticator](https://github.com/mattrubin/Authenticator) handles this can be found here:
https://github.com/mattrubin/Authenticator/blob/6dcffbde4a16bbb42bf9ffa049821a43e7484359/Authenticator/Source/TokenStore.swift#L86-L100
