### ISSUE TITLE
How can I calculate the Time Remaining on the current code?

### ISSUE THREAD

**Issue by chrisjrex** [mattrubin/OneTimePassword#185]
I'm displaying a count down for the current token to the user, much like Google authenticator or Authy. 
Except I need to know how much time is remaining on that token, so that I can set the UI to be correct & update the UI at the right time.

Is there an easy calculation for this? or could this be added to the framework? I think it would be quite vital for the implementation

**Comment by mattrubin** [comment]
Some example code for how to calculate the last and next update time for a token can be found in the [Authenticator](https://github.com/mattrubin/Authenticator) source code:
https://github.com/mattrubin/Authenticator/blob/6dcffbde4a16bbb42bf9ffa049821a43e7484359/Authenticator/Source/TokenList.swift#L151-L169

Based on this code, calculating the time remaining on the token should be fairly trivial. Something like:
```
(period - currentTimeIntervalSince1970.truncatingRemainder(dividingBy: period)
```

I'll leave this issue open for now while I consider whether moving this functionality into the framework would be useful without adding too much additional complexity.
