### ISSUE TITLE
How can we decode the generated Token, if its valid or not ?

### ISSUE THREAD

**Issue by kbs95** [mattrubin/OneTimePassword#193]
Generation has been explained properly, but can you tell me how can we decode the secret, on other client's app to validate the token.

**Comment by mattrubin** [comment]
I'm not certain I understand the question, but I think you may be asking how to use the one-password to authenticate a user?

The one-time password that is generated will not (and cannot) be decoded. To validate the OTP, the validating web site or service must also have a copy of the user's secret key, and must also generate a password from that key. By comparing the passwords, the validating service can determine whether the user is in possession of the secret key.

You may find more useful info in the RFCs which define hash-based and time-based one-time passwords:
https://tools.ietf.org/html/rfc4226
https://tools.ietf.org/html/rfc6238

**Comment by kbs95** [comment]
Thank you for quick response.
