### ISSUE TITLE
Any reason CocoaPods/Specs only has v1.1 instead of 2.0 of your Podspec? 

### ISSUE THREAD

**Issue by freak4pc** [mattrubin/OneTimePassword#2]

**Comment by mattrubin** [comment]
Version 2 is still in beta. When OneTimePassword 2.0 is finalized, I'll update the CocoaPods spec.

**Comment by mattrubin** [comment]
Version 2 is [now available via CocoaPods](https://cocoapods.org/pods/OneTimePassword).
