### ISSUE TITLE
Swift 5 compatibility

### ISSUE THREAD

**Issue by gereons** [mattrubin/OneTimePassword#207]
OneTimePassword is the last of the dependencies we use at my company to show up in the "Migrate to Swift 5" list in Xcode. The necessary changes to add Swift 5 conformance boil down to two small `#if swift(>= 5.0)` sections and the declaration of version compatibiliy in the .podspec via the new `s.swift_versions` property that just became available in CocoaPods 1.7.0. 

Before posting this PR, I wanted to make sure if this the right approach?
https://github.com/snabble/OneTimePassword/commit/cb145c06bcba6a127eb4cb8eaa67e342029b692a

**Comment by mattrubin** [comment]
This approach looks good to me! A PR is much appreciated, though I won't be able to review it for about a week due to other commitments.
