### ISSUE TITLE
Support macOS with a new release with updated podspec and SPM support

### ISSUE THREAD

**Issue by santhoshramaraju** [mattrubin/OneTimePassword#261]
The podspec in the latest release 3.2.0 has platform restrictions but I see the develop branch's podspec doesn't. Also the develop branch has a Package.swift to support SPM but the latest release doesn't. When would the next release be to update the podspec in the cocoapods repo and support SPM?

**Comment by santhoshramaraju** [comment]
@mattrubin can you please look into this?

**Comment by mattrubin** [comment]
The upcoming 4.0 release adds support for macOS and Swift Package Manager (although it no longer supports CocoaPods – see https://github.com/mattrubin/OneTimePassword/pull/249). I can't promise when 4.0 will be ready for release, but in the meantime you're welcome to use the latest prerelease version via [the `4.0.0-pre.0` tag](https://github.com/mattrubin/OneTimePassword/releases/tag/4.0.0-pre.0).
