### ISSUE TITLE
Unable to add via SPM. 

### ISSUE THREAD

**Issue by mafhaam** [mattrubin/OneTimePassword#265]
When trying to add giving this error: 

<img width="716" alt="Screenshot 2023-07-25 at 12 12 07 AM" src="https://github.com/mattrubin/OneTimePassword/assets/123963056/04f320c9-fa53-4216-a218-d268c855b958">

**Comment by leoparenti** [comment]
The problem is Package.swift was generated with "// swift-tools-version:5.1"

I have done the PR for fix it (https://github.com/mattrubin/OneTimePassword/pull/266) and a fork if u need:

`.package(url: "https://github.com/leoparenti/OneTimePassword", from: "3.2.1"),`

**Comment by djangdal** [comment]
@leoparenti the repo at https://github.com/leoparenti/OneTimePassword is private

**Comment by krypt-lx** [comment]
The example from readme.md gives me an issue too:
> error: Dependencies could not be resolved because no versions of 'onetimepassword' match the requirement 4.0.0..<5.0.0 and root depends on 'onetimepassword' 4.0.0..<5.0.0.

**Comment by leoparenti** [comment]
so I ask A pull request to add fix for Swift 5.8
https://github.com/mattrubin/OneTimePassword/pull/268

sorry I set My repo public again
https://github.com/leoparenti/OneTimePassword

**Comment by krypt-lx** [comment]
In same case in another lib I used `.package(url:revision:)` to specify commit containing a valid package.swift 

WIth this lib, though, its dependency do not work in modern SPM for me anymore (had to clone it and update the project settings: ObjC bridging related issues)
