### ISSUE TITLE
import Base32, import CommonCrypto No such modules

### ISSUE THREAD

**Issue by antoine-ki** [mattrubin/OneTimePassword#28]
Hi,

import Base32
import CommonCrypto

no such modules.

1- removed the CommonCrypto import (worked)
2- What do i do for the import Base32? The library is only used while parsing the secret.

Help :p

**Comment by mattrubin** [comment]
These dependencies are included in the framework via Git submodules, and are built as target dependencies. You need to:

 - Check out the project's dependencies with `git submodule init` and `git submodule update`.
 - Open the `OneTimePassword.xcworkspace` file. This workspace includes the OneTimePassword `xcodeproj`, and also the Xcode projects of the required dependencies, so they can all be built and linked together.

I've added instructions to the project README (#34) which will hopefully clarify the process for getting and building the dependencies.
