### ISSUE TITLE
Support watchOS through Carthage

### ISSUE THREAD

**Issue by jessemx109** [mattrubin/OneTimePassword#81]
Hey it would be awesome if you could get a version of this framework working with watchOS. I want to include it in my project and will be using it on the watch

From a little research I believe the only thing that needs to be done is to add a target in the Base32 library that targets watchOS

Support for this would be awesome and thanks in advance

**Comment by mattrubin** [comment]
A watchOS target was added in PR #96, and will be available in the [2.1 release](https://github.com/mattrubin/OneTimePassword/milestone/6).
