### ISSUE TITLE
A lot of errors in 'swift-3" branch when trying to build with latest Xcode (Version 8.0 (8A218a))

### ISSUE THREAD

**Issue by ramunasjurgilas** [mattrubin/OneTimePassword#85]
It is not possible to build "swift-3" branch. Generates a lot of errors. Some of them is bellow:
Generator.swift:81:27: 'withUnsafePointer' has been renamed to 'withUnsafePointer(to:_:)'
Generator.swift:82:44: 'init' is unavailable: use 'withMemoryRebound(to:capacity:_)' to temporarily view memory as another layout-compatible type.

**Comment by mattrubin** [comment]
These errors are fixed by #91.
