### ISSUE TITLE
Swift 3 Update

### ISSUE THREAD

**Issue by code-draft** [mattrubin/OneTimePassword#93]
Hi, can you update the code for swift 3. It would be great of you to help me out

**Comment by mattrubin** [comment]
The Swift 3 version is still a work in progress. You can use it now from the [`swift-3`](https://github.com/mattrubin/OneTimePassword/tree/swift-3) branch, but know that [the public API is likely to change](https://github.com/mattrubin/OneTimePassword/pull/80).

**Comment by bobloos93** [comment]
@mattrubin Can you tell me when a release will be made with the Swift 3-support?

**Comment by RolandTalvar** [comment]
Hi @mattrubin 

I'm also very interested in Swift 3 version. Any information about when it's available through Cocoapods?

All the best
Roland

**Comment by mattrubin** [comment]
OneTimePassword 3.0 for Swift 3 is [now available](https://github.com/mattrubin/OneTimePassword/releases/tag/3.0)!
Thanks all for your patience. If 3.0 gives you any problems, please let me know.
